version: '3.8'

services:
  app:
    container_name: go_service
    # image: nexus.io.xunison.com/repository/go-service-template-master:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: settings.env
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - service_network
    depends_on:
      - postgresql

  postgresql:
    image: 'bitnami/postgresql:16'
    environment:
      - POSTGRESQL_USERNAME=yuri
      - POSTGRESQL_PASSWORD=777
      - POSTGRESQL_DATABASE=iot
    ports:
      - 5432:5432
    volumes:
      - $PWD/postgresql_data:/bitnami/postgresql
    networks:
      - service_network

networks:
  service_network:
